### ISSUE TITLE
Support Jest fake timers

### ISSUE THREAD

**Issue by tyteen4a03** [date-fns/utc#4]
Does this package offer integration with Jest fakeTImers?

**Comment by kossnocorp** [comment]
Not at this moment, and I'm not sure what it will take to support those and if it makes sense. Can you please explain the use case with code examples so I can decide if it's something I have to explore? Closing the issue for now.

**Comment by tyteen4a03** [comment]
I would like to do `new UTCDate()` as I do `new Date()` - Jest fakeTimers is able to intercept the latter and mock its outputs but doesn't support the former.

**Comment by kossnocorp** [comment]
@tyteen4a03 I got you, but did you try doing it? [You can see that `UTCDate` extends `Date`](https://github.com/date-fns/utc/blob/main/src/date/mini.mjs), and as long as `Date` is mocked, `UTCDate` should be mocked through the prototype chain if I understand how Jest works correctly.

**Comment by thommeo** [comment]
I have the same problem. Jest fake timers use sinon/fake-timers under the hood. It replaces the global Date object with a mock. The way UTCDate is implemented is it copies exiting methods from global Date on first require, which happens before we call `jest.useFakeTimers()` in the test.

Even if we clear require cache and force execute this method copying logic, the UTCDate class that has been imported by the actual business logic code will remain intact.

In order for it to work the methods should not be copied but created as transparent calls to the original methods on global date object.

**Comment by kossnocorp** [comment]
I added support for it in `@date-fns/utc@1.2.0`. Please check if it works and report if something is missing. I don't have an actual test suite to test it.

See the implementation: https://github.com/date-fns/utc/commit/08d4b778dff985ce472a9bc4993630a66292221f

**Comment by lee-admiral** [comment]
I am still seeing issues with this when using the UTCDate.now().
