### ISSUE TITLE
LICENSE.md file is missing (but listed as MIT in package.json)

### ISSUE THREAD

**Issue by jamiecopeland** [date-fns/utc#8]
First off thank you! This package has made so many things easer, especially dealing with dates over long ranges that involve DST shifts 🥰.

The `package.json` has the license down as MIT, but the `LICENSE.md` file seems to be missing from the repo.

Lots of companies have strict rules around package usage and this may be a blocker in some cases.

I can create a PR with the same MIT `LICENSE.md` from the main date-fns library if that's any help?

**Comment by kossnocorp** [comment]
Hey! Thank you for the heads up. It was always MIT. I just forgot to add the file. I've added `LICENSE.md` and will ship with the next version if it makes any difference.
